name: ecommerce

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
      POSTGRES_DB: ecommerce
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce

  products_service:
    build: ./products
    container_name: products_service
    environment:
      HOST: db
      USERNAME: ecommerce_user
      PASSWORD: ecommerce_password
      DATABASE: ecommerce
    depends_on:
      - db
    networks:
      - ecommerce

  user_service:
    build: ./user
    container_name: user_service
    environment:
      HOST: db
      USERNAME: ecommerce_user
      PASSWORD: ecommerce_password
      DATABASE: ecommerce
    depends_on:
      - db
    networks:
      - ecommerce

  orders_service:
    build: ./orders
    container_name: orders_service
    environment:
      HOST: db
      USERNAME: ecommerce_user
      PASSWORD: ecommerce_password
      DATABASE: ecommerce
    depends_on:
      - db
    networks:
      - ecommerce

  reverse_proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - products_service
      - user_service
      - orders_service
    networks:
      - ecommerce

volumes:
  postgres_data:

networks:
  ecommerce:
    driver: bridge
